filebeat.inputs:
- type: log
  paths:
    - /var/log/messages

- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
# Enrich the docker logs with useful information, such as the name of the image or the name of the container
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
# Settings concern FileBeat own logs. They are not mandatory but they make the logs more readable in Kibana.
logging.json: true
logging.metrics.enabled: false