package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Demo2_BuildCatalogue'
in the project with id = 'Demo2', and delete the patch script.
*/
create(RelativeId("Demo2"), BuildType({
    id("Demo2_BuildCatalogue")
    name = "Build catalogue"

    vcs {
        root(RelativeId("Demo2_Catalogue"))
    }

    steps {
        dockerCommand {
            commandType = build {
                source = path {
                    path = "docker/catalogue/Dockerfile"
                }
            }
        }
    }
}))

