package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Demo3_CartsRepoToBuid'
in the project with id = 'Demo3', and delete the patch script.
*/
create(RelativeId("Demo3"), GitVcsRoot({
    id("Demo3_CartsRepoToBuid")
    name = "Carts_repo_to_buid"
    url = "https://github.com/TarasKindrat/carts.git"
}))

