---
- name: "Create elastic volume"
  docker_volume:
    name: "{{ elastic_volume }}"

- name: "Create a network"
  docker_network:
    name: "{{ elastic_network }}"
    driver: overlay
    state: present
    attachable: yes

- name: "Launch elasticsearch container"
  docker_container:
    name: "elasticsearch"
    image: "docker.elastic.co/elasticsearch/elasticsearch:{{ elk_version }}"
    volumes:
      - "{{ elastic_volume }}:/usr/share/elasticsearch/data"
    restart_policy: unless-stopped
    network_mode: "{{ elastic_network }}"
    state: started
    detach: yes
    env:
        discovery.type: "single-node"
    published_ports: "9200:9200"
 
- name: "Launch kibana container"
  docker_container:
    name: "kibana"
    image: "docker.elastic.co/kibana/kibana:{{ elk_version }}"
    restart_policy: unless-stopped
    network_mode: "{{ elastic_network }}"
    state: started
    detach: yes
    published_ports: "5601:5601"